ADR-748: Tax Type Code feature added
hmrc/alcohol-duty-ui-tests pull request #30
Opened 2024-01-12 14:46 UTC by chiransan01

2024-01-12 16:19 UTC, yasaracar requested changes

2024-01-12 16:19 UTC, yasaracar commented on src/test/resources/features/alcoholToDeclare/AlcoholDutyReturns.feature
> +    When I select radio button "Other fermented products, tax type code 301" on "Tax Type Page"
Can we also the verify the eac tax type code visible ion the list for all these scenarios?

2024-01-12 16:24 UTC, chiransan01 commented on src/test/resources/features/alcoholToDeclare/AlcoholDutyReturns.feature
> +    When I select radio button "Other fermented products, tax type code 301" on "Tax Type Page"
Yes, we can do. I will amend the tests to capture this information

2024-01-15 09:36 UTC, yasaracar approved these changes

2024-01-15 12:25 UTC, merged